language: java
sudo: true
notifications:
  slack: sem5640-2018:lBYoMLDBbIP1GGlCH2tQcjho

cache:
  directories:
    - $HOME/.m2

before_install:
  - git clone https://github.com/sem5640-2018/deployment.git --depth=1
  # Ensure that syslog is running etc
  - sudo docker-compose up -d

install: 
  # Build dependencies first so it goes away
  - mvn dependency:resolve
script: 
  - mvn test -B
  # Package into WAR
  - mvn war:exploded

after_success:
  # Conditional stages do not work so this is the current "solution"
  # Production
  - test $TRAVIS_BRANCH = "master" && test $TRAVIS_PULL_REQUEST = "false" && 
    echo "Creating PROD docker image" &&
    docker build -f Dockerfile -t glados:$TRAVIS_COMMIT .

  # Staging
  - test $TRAVIS_BRANCH = "development" && test $TRAVIS_PULL_REQUEST = "false" && 
    echo "Creating STAGING docker image" &&
    docker build -f Dockerfile -t glados-staging:$TRAVIS_COMMIT .

  # TODO push to docker hub and call web hook