language: java
sudo: required
notifications:
  slack: sem5640-2018:lBYoMLDBbIP1GGlCH2tQcjho

cache:
  directories:
    - $HOME/.m2

services:
  - docker

stages:
  - test
  - name: build_staging
    if: branch = development AND type = push
  - name: build_release
    if: branch = master AND type = push

jobs:
  include:
    - stage: test
      name: "Tests"
      install: 
      # Build dependencies first so it goes away
      - mvn dependency:resolve
      script: 
      - mvn test -B
      - mvn war:exploded
    - stage: build_staging
      name: "Build docker staging image"
      script:
       # TODO log in to docker
       - docker build -t glados:$TRAVIS_COMMIT .
       # TODO push to docker hub
    - stage: build_release
      name: "Build docker release image"
      script:
        # TODO log in to docker
       - docker build -t glados:latest .
       # TODO push to docker hub